In [1]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
#from sklearn.metrics import mean_squared_error
from math import sqrt
#from sklearn.metrics import r2_score


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/wine.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Wine                  178 non-null    int64  
 1   Alcohol               178 non-null    float64
 2   Malic.acid            178 non-null    float64
 3   Ash                   178 non-null    float64
 4   Acl                   178 non-null    float64
 5   Mg                    178 non-null    int64  
 6   Phenols               178 non-null    float64
 7   Flavanoids            178 non-null    float64
 8   Nonflavanoid.phenols  178 non-null    float64
 9   Proanth               178 non-null    float64
 10  Color.int             178 non-null    float64
 11  Hue                   178 non-null    float64
 12  OD                    178 non-null    float64
 13  Proline               178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [4]:
df.head(10)

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   
5     1    14.20        1.76  2.45  15.2  112     3.27        3.39   
6     1    14.39        1.87  2.45  14.6   96     2.50        2.52   
7     1    14.06        2.15  2.61  17.6  121     2.60        2.51   
8     1    14.83        1.64  2.17  14.0   97     2.80        2.98   
9     1    13.86        1.35  2.27  16.0   98     2.98        3.15   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735  
5                  0.34     1.97       6.75  1.05  2.85     1450  
6                  0.30     1.98       5.25  1.02  3.58     1290  
7                  0.31     1.25       5.05  1.06  3.58     1295  
8                  0.29     1.98       5.20  1.08  2.85     1045  
9                  0.22     1.85       7.22  1.01  3.55     1045

In [5]:
df = df.sample(frac = 1)

In [6]:
df.head(10)

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
11      1    14.12        1.48  2.32  16.8   95     2.20        2.43   
72      2    13.49        1.66  2.24  24.0   87     1.88        1.84   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
59      2    12.37        0.94  1.36  10.6   88     1.98        0.57   
108     2    12.22        1.29  1.94  19.0   92     2.36        2.04   
33      1    13.76        1.53  2.70  19.5  132     2.95        2.74   
145     3    13.16        3.57  2.15  21.0  102     1.50        0.55   
164     3    13.78        2.76  2.30  22.0   90     1.35        0.68   
114     2    12.08        1.39  2.50  22.5   84     2.56        2.29   
99      2    12.29        3.17  2.21  18.0   88     2.85        2.99   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
11                   0.26     1.57       5.00  1.17  2.82     1280  
72                   0.27     1.03       3.74  0.98  2.78      472  
175                  0.43     1.35      10.20  0.59  1.56      835  
59                   0.28     0.42       1.95  1.05  1.82      520  
108                  0.39     2.08       2.70  0.86  3.02      312  
33                   0.50     1.35       5.40  1.25  3.00     1235  
145                  0.43     1.30       4.00  0.60  1.68      830  
164                  0.41     1.03       9.58  0.70  1.68      615  
114                  0.43     1.04       2.90  0.93  3.19      385  
99                   0.45     2.81       2.30  1.42  2.83      406

In [7]:
#Import the Data
df = pd.read_csv('/content/drive/MyDrive/wine.csv')
print(df.shape)
df.describe().transpose()

(178, 14)


count        mean         std     min       25%  \
Wine                  178.0    1.938202    0.775035    1.00    1.0000   
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic.acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Acl                   178.0   19.494944    3.339564   10.60   17.2000   
Mg                    178.0   99.741573   14.282484   70.00   88.0000   
Phenols               178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid.phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanth               178.0    1.590899    0.572359    0.41    1.2500   
Color.int             178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD                    178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Wine                    2.000    3.0000     3.00  
Alcohol                13.050   13.6775    14.83  
Malic.acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Acl                    19.500   21.5000    30.00  
Mg                     98.000  107.0000   162.00  
Phenols                 2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid.phenols    0.340    0.4375     0.66  
Proanth                 1.555    1.9500     3.58  
Color.int               4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD                      2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [10]:
df["Wine"].astype('object')

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: object

In [11]:
print (df['Wine'].unique())

[1 2 3]


In [12]:
df['Wine'] = df['Wine'].map({1: '1', 2: '2', 3: '3'})

In [13]:
df.describe().transpose()

count        mean         std     min       25%  \
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic.acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Acl                   178.0   19.494944    3.339564   10.60   17.2000   
Mg                    178.0   99.741573   14.282484   70.00   88.0000   
Phenols               178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid.phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanth               178.0    1.590899    0.572359    0.41    1.2500   
Color.int             178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD                    178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Alcohol                13.050   13.6775    14.83  
Malic.acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Acl                    19.500   21.5000    30.00  
Mg                     98.000  107.0000   162.00  
Phenols                 2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid.phenols    0.340    0.4375     0.66  
Proanth                 1.555    1.9500     3.58  
Color.int               4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD                      2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [14]:
df.describe(include=object).transpose()

count unique top freq
Wine   178      3   2   71

In [15]:
#Let’s set up and split our Data and our Labels
X = df.drop('Wine',axis=1)
y = df['Wine']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
#Scale the Train and Test Data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)
StandardScaler(copy=True, with_mean=True, with_std=True)

# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
%%time

from sklearn.model_selection import GridSearchCV

params = {'activation': ['relu', 'tanh', 'logistic', 'identity'],
          'hidden_layer_sizes': [(13,), (50,100,), (50,75,100,)],
          'solver': ['adam', 'sgd', 'lbfgs'],
          'learning_rate' : ['constant', 'adaptive', 'invscaling'],
          'max_iter': [500]
         }

mlp_classif_grid = GridSearchCV(MLPClassifier(random_state=123), param_grid=params, n_jobs=-1, cv=5, verbose=5)
mlp_classif_grid.fit(X_train,y_train)

print('Train Accuracy : %.3f'%mlp_classif_grid.best_estimator_.score(X_train, y_train))
print('Test Accuracy : %.3f'%mlp_classif_grid.best_estimator_.score(X_test, y_test))
print('Best Accuracy Through Grid Search : %.3f'%mlp_classif_grid.best_score_)
print('Best Parameters : ',mlp_classif_grid.best_params_)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
Train Accuracy : 1.000
Test Accuracy : 0.956
Best Accuracy Through Grid Search : 0.992
Best Parameters :  {'activation': 'logistic', 'hidden_layer_sizes': (50, 75, 100), 'learning_rate': 'constant', 'max_iter': 500, 'solver': 'lbfgs'}
CPU times: user 3.54 s, sys: 889 ms, total: 4.43 s
Wall time: 2min 33s


In [19]:
mlp = MLPClassifier(activation= 'tanh', hidden_layer_sizes= (50,100), learning_rate='constant', solver='lbfgs', max_iter=500)
mlp.fit(X_train,y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=(50, 100), max_iter=500,
              solver='lbfgs')

In [20]:
predictions = mlp.predict(X_test)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[10  0  0]
 [ 1 16  0]
 [ 0  0 18]]


In [22]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.91      1.00      0.95        10
           2       1.00      0.94      0.97        17
           3       1.00      1.00      1.00        18

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45

